// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  models

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( MessageList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* MessageList ) UnmarshalJSON([]byte) error { return nil }
func ( MessageList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* MessageList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_MessageList *MessageList
