// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson750e3c9dDecodeGithubComDEEBBLUEModelsModels(in *jlexer.Lexer, out *User) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "tg_id":
			out.TgId = int(in.Int())
		case "chat_id":
			out.ChatId = int(in.Int())
		case "owner_id":
			out.OwnerId = int(in.Int())
		case "verif_status":
			out.VerifStatus = string(in.String())
		case "role":
			out.Role = string(in.String())
		case "balance":
			out.Balance = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson750e3c9dEncodeGithubComDEEBBLUEModelsModels(out *jwriter.Writer, in User) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"tg_id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.TgId))
	}
	{
		const prefix string = ",\"chat_id\":"
		out.RawString(prefix)
		out.Int(int(in.ChatId))
	}
	{
		const prefix string = ",\"owner_id\":"
		out.RawString(prefix)
		out.Int(int(in.OwnerId))
	}
	{
		const prefix string = ",\"verif_status\":"
		out.RawString(prefix)
		out.String(string(in.VerifStatus))
	}
	{
		const prefix string = ",\"role\":"
		out.RawString(prefix)
		out.String(string(in.Role))
	}
	{
		const prefix string = ",\"balance\":"
		out.RawString(prefix)
		out.Int(int(in.Balance))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v User) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson750e3c9dEncodeGithubComDEEBBLUEModelsModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v User) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson750e3c9dEncodeGithubComDEEBBLUEModelsModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *User) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson750e3c9dDecodeGithubComDEEBBLUEModelsModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *User) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson750e3c9dDecodeGithubComDEEBBLUEModelsModels(l, v)
}
